"use client";

import { useCallback, useRef } from "react";
import type { ScoredTrack } from "@/types";
import { MAX_PER_PLAYLIST } from "@/lib/config";

interface CreateActions {
  setProgress: (progress: {
    partsCreated?: number;
    tracksAdded?: number;
    tracksFailed?: number;
    currentPart?: number;
    done?: boolean;
    isRunning?: boolean;
  }) => void;
  addCreatedPlaylist: (playlist: {
    id: number;
    title: string;
    trackCount: number;
    url: string;
  }) => void;
}

export function useSCPlaylistCreate(actions: CreateActions) {
  const abortRef = useRef(false);

  const createPlaylists = useCallback(
    async (
      tracks: ScoredTrack[],
      baseTitle: string,
      sharing: "public" | "private"
    ) => {
      abortRef.current = false;

      if (tracks.length === 0) {
        console.error("[CreatePlaylist] No tracks to add");
        return;
      }

      const totalParts = Math.ceil(tracks.length / MAX_PER_PLAYLIST);
      actions.setProgress({
        partsCreated: 0,
        tracksAdded: 0,
        tracksFailed: 0,
        currentPart: 1,
        done: false,
        isRunning: true,
      });

      try {
        let totalAdded = 0;
        let totalFailed = 0;

        for (let part = 0; part < totalParts; part++) {
          if (abortRef.current) break;

          const partNum = part + 1;
          const title =
            totalParts === 1
              ? baseTitle
              : `${baseTitle} \u2014 Part ${String(partNum).padStart(2, "0")}`;
          const description = `Playlist generated by CrateMine on ${new Date().toISOString().slice(0, 10)}.`;

          actions.setProgress({ currentPart: partNum });

          // Get track IDs for this chunk
          const chunkStart = part * MAX_PER_PLAYLIST;
          const chunkEnd = Math.min(chunkStart + MAX_PER_PLAYLIST, tracks.length);
          const chunkIds = tracks.slice(chunkStart, chunkEnd).map((t) => t.trackId);

          // Create playlist with all tracks in one POST call
          // (bypasses the broken PUT /playlists/{id} endpoint)
          const createResp = await fetch("/api/sc/create-playlist", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ title, description, sharing, trackIds: chunkIds }),
          });

          if (!createResp.ok) {
            const err = await createResp.json().catch(() => ({ error: `HTTP ${createResp.status}` }));
            console.error("[CreatePlaylist] Create failed:", err);
            throw new Error(err.error || `Failed to create playlist part ${partNum}`);
          }

          const { playlist } = await createResp.json();

          totalAdded += chunkIds.length;
          actions.setProgress({
            tracksAdded: totalAdded,
            tracksFailed: totalFailed,
          });

          actions.addCreatedPlaylist({
            id: playlist.id,
            title,
            trackCount: chunkIds.length,
            url: playlist.permalink_url,
          });

          actions.setProgress({ partsCreated: partNum });
        }

        actions.setProgress({ done: true, isRunning: false });
      } catch (err) {
        console.error("[CreatePlaylist] Error:", err);
        actions.setProgress({ done: false, isRunning: false });
      }
    },
    [actions]
  );

  const abort = useCallback(() => {
    abortRef.current = true;
  }, []);

  return { createPlaylists, abort };
}
