"use client";

import type { WizardState } from "@/types";

interface Props {
  outputTitle: string;
  outputSharing: "public" | "private";
  trackCount: number;
  progress: WizardState["creationProgress"];
  createdPlaylists: WizardState["createdPlaylists"];
  onTitleChange: (title: string) => void;
  onSharingChange: (sharing: "public" | "private") => void;
  onCreate: () => void;
  onBack: () => void;
  onReset: () => void;
}

export function CreateStep({
  outputTitle,
  outputSharing,
  trackCount,
  progress,
  createdPlaylists,
  onTitleChange,
  onSharingChange,
  onCreate,
  onBack,
  onReset,
}: Props) {
  return (
    <div className="space-y-6">
      <h2 className="text-xl font-semibold text-white">Create Playlist</h2>

      {!progress.done && (
        <div className="space-y-4">
          <div>
            <label className="block text-sm text-zinc-400 mb-1">
              Playlist title
            </label>
            <input
              type="text"
              className="w-full bg-zinc-900 border border-zinc-700 rounded-lg p-3 text-white focus:border-orange-500 focus:outline-none"
              value={outputTitle}
              onChange={(e) => onTitleChange(e.target.value)}
              placeholder="My Merged Playlist"
            />
          </div>

          <div>
            <p className="text-xs text-zinc-500 mt-1">
              Description will include: <span className="text-zinc-400">Playlist generated by CrateMine</span>
            </p>
          </div>

          <div>
            <label className="block text-sm text-zinc-400 mb-1">Visibility</label>
            <div className="flex gap-4">
              <label className="flex items-center gap-2 text-white cursor-pointer">
                <input
                  type="radio"
                  name="sharing"
                  value="public"
                  checked={outputSharing === "public"}
                  onChange={() => onSharingChange("public")}
                  className="accent-orange-500"
                />
                Public
              </label>
              <label className="flex items-center gap-2 text-white cursor-pointer">
                <input
                  type="radio"
                  name="sharing"
                  value="private"
                  checked={outputSharing === "private"}
                  onChange={() => onSharingChange("private")}
                  className="accent-orange-500"
                />
                Private
              </label>
            </div>
          </div>

          <div className="flex items-center gap-4">
            <button
              onClick={onBack}
              disabled={progress.isRunning}
              className="px-6 py-2 bg-zinc-700 hover:bg-zinc-600 disabled:bg-zinc-800 text-white font-medium rounded-lg transition-colors"
            >
              Back
            </button>
            <button
              onClick={onCreate}
              disabled={!outputTitle.trim() || progress.isRunning}
              className="px-6 py-2 bg-orange-500 hover:bg-orange-600 disabled:bg-zinc-700 disabled:text-zinc-500 text-white font-medium rounded-lg transition-colors"
            >
              {progress.isRunning
                ? "Creating..."
                : `Create playlist (${trackCount.toLocaleString()} tracks)`}
            </button>
          </div>
        </div>
      )}

      {createdPlaylists.length > 0 && (
        <div className="space-y-3">
          <h3 className="text-lg font-medium text-white">
            {progress.done ? "Done!" : "Created so far:"}
          </h3>
          {createdPlaylists.map((pl) => (
            <div
              key={pl.id}
              className="flex items-center justify-between bg-zinc-900 rounded-lg p-4"
            >
              <div>
                <p className="text-white font-medium">{pl.title}</p>
                <p className="text-sm text-zinc-400">
                  {pl.trackCount} tracks
                </p>
              </div>
              <a
                href={pl.url}
                target="_blank"
                rel="noopener noreferrer"
                className="px-4 py-2 bg-orange-500 hover:bg-orange-600 text-white text-sm font-medium rounded-lg transition-colors"
              >
                Open on SoundCloud
              </a>
            </div>
          ))}

          {progress.done && (
            <button
              onClick={onReset}
              className="px-6 py-2 bg-zinc-700 hover:bg-zinc-600 text-white font-medium rounded-lg transition-colors"
            >
              Start over
            </button>
          )}
        </div>
      )}
    </div>
  );
}
