"use client";

import { motion } from "framer-motion";
import type { WizardState } from "@/types";
import { ProgressBar } from "@/components/ui/ProgressBar";

interface Props {
  outputTitle: string;
  outputSharing: "public" | "private";
  trackCount: number;
  progress: WizardState["creationProgress"];
  createdPlaylists: WizardState["createdPlaylists"];
  onTitleChange: (title: string) => void;
  onSharingChange: (sharing: "public" | "private") => void;
  onCreate: () => void;
  onBack: () => void;
  onReset: () => void;
  removeBranding?: boolean;
}

export function CreateStep({
  outputTitle,
  outputSharing,
  trackCount,
  progress,
  createdPlaylists,
  onTitleChange,
  onSharingChange,
  onCreate,
  onBack,
  onReset,
  removeBranding = false,
}: Props) {
  const totalTracks = createdPlaylists.reduce((s, p) => s + p.trackCount, 0);

  return (
    <div className="space-y-6">
      <h2 className="text-xl font-semibold text-white">Create Playlist</h2>

      {!progress.done && (
        <div className="space-y-4">
          <div>
            <label className="block text-sm text-zinc-400 mb-1">
              Playlist title
            </label>
            <input
              type="text"
              className="w-full bg-zinc-900 border border-zinc-700 rounded-lg p-3 text-white focus:border-orange-500 focus:outline-none"
              value={outputTitle}
              onChange={(e) => onTitleChange(e.target.value)}
              placeholder="My Merged Playlist"
            />
          </div>

          {!removeBranding ? (
            <p className="text-xs text-zinc-500">
              Description will include:{" "}
              <span className="text-zinc-400">
                Playlist generated by CrateMine
              </span>
              {" · "}
              <a href="/dashboard/pricing" className="text-orange-400/60 hover:text-orange-400 transition-colors">
                Remove with Pro
              </a>
            </p>
          ) : (
            <p className="text-xs text-zinc-500">
              No CrateMine branding will be added.
            </p>
          )}

          <div>
            <label className="block text-sm text-zinc-400 mb-1">
              Visibility
            </label>
            <div className="flex gap-2">
              {(["public", "private"] as const).map((opt) => (
                <button
                  key={opt}
                  onClick={() => onSharingChange(opt)}
                  className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors cursor-pointer capitalize ${
                    outputSharing === opt
                      ? "bg-orange-500 text-white"
                      : "bg-zinc-800 text-zinc-400 hover:text-white"
                  }`}
                >
                  {opt}
                </button>
              ))}
            </div>
          </div>

          {progress.isRunning && (
            <ProgressBar
              completed={progress.tracksAdded}
              total={trackCount}
              label="Creating playlist"
            />
          )}

          <div className="flex items-center gap-4">
            <button
              onClick={onBack}
              disabled={progress.isRunning}
              className="px-6 py-2 bg-zinc-700 hover:bg-zinc-600 disabled:bg-zinc-800 text-white font-medium rounded-lg transition-colors cursor-pointer"
            >
              Back
            </button>
            <button
              onClick={onCreate}
              disabled={!outputTitle.trim() || progress.isRunning}
              className="px-6 py-2 bg-orange-500 hover:bg-orange-600 disabled:bg-zinc-700 disabled:text-zinc-500 text-white font-medium rounded-lg transition-colors cursor-pointer"
            >
              {progress.isRunning
                ? "Creating..."
                : `Create playlist (${trackCount.toLocaleString()} tracks)`}
            </button>
          </div>
        </div>
      )}

      {progress.done && createdPlaylists.length > 0 && (
        <div className="space-y-6">
          {/* Celebratory header */}
          <div className="text-center py-4">
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              transition={{ type: "spring", stiffness: 200, damping: 12 }}
              className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-green-500/10 mb-4"
            >
              <svg
                className="w-8 h-8 text-green-400"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                strokeWidth={2.5}
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M5 13l4 4L19 7"
                />
              </svg>
            </motion.div>
            <motion.h3
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className="text-xl font-semibold text-white"
            >
              Playlist created!
            </motion.h3>
            <motion.p
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.3 }}
              className="text-sm text-zinc-400 mt-1"
            >
              {totalTracks.toLocaleString()} tracks across{" "}
              {createdPlaylists.length} playlist
              {createdPlaylists.length !== 1 ? "s" : ""}
            </motion.p>
          </div>

          {/* Playlist cards */}
          {createdPlaylists.map((pl, i) => (
            <motion.div
              key={pl.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 + i * 0.1 }}
              className="flex items-center justify-between bg-zinc-900 rounded-lg p-4"
            >
              <div>
                <p className="text-white font-medium">{pl.title}</p>
                <p className="text-sm text-zinc-400">
                  {pl.trackCount} tracks
                </p>
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => {
                    navigator.clipboard.writeText(pl.url);
                  }}
                  className="px-3 py-2 bg-zinc-800 hover:bg-zinc-700 text-zinc-300 text-sm rounded-lg transition-colors cursor-pointer"
                  title="Copy link"
                >
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" />
                  </svg>
                </button>
                <a
                  href={pl.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-4 py-2 bg-orange-500 hover:bg-orange-600 text-white text-sm font-medium rounded-lg transition-colors"
                >
                  Open on SoundCloud
                </a>
              </div>
            </motion.div>
          ))}

          <button
            onClick={onReset}
            className="px-6 py-2 bg-zinc-700 hover:bg-zinc-600 text-white font-medium rounded-lg transition-colors cursor-pointer"
          >
            Start over
          </button>
        </div>
      )}
    </div>
  );
}
