import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { getValidSCToken } from "@/lib/soundcloud/tokens";
import { createPlaylist } from "@/lib/soundcloud/playlist-create";
import { verifyCsrf } from "@/lib/csrf";
import { getEffectivePlan } from "@/lib/plans";

/**
 * Create an empty playlist on SoundCloud.
 * POST body: { title: string, description: string, sharing: "public" | "private" }
 */
export async function POST(request: NextRequest) {
  const csrfError = verifyCsrf(request);
  if (csrfError) return csrfError;

  const session = await auth();
  if (!session?.user) {
    return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
  }

  const token = await getValidSCToken();
  if (!token) {
    return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
  }

  const { title, description, sharing, trackIds } = await request.json();

  if (!title) {
    return NextResponse.json({ error: "Missing title" }, { status: 400 });
  }

  // Check plan for branding
  const planConfig = getEffectivePlan(
    (session.user as { plan?: string }).plan || "free",
    session.user.role || "user"
  );

  const BRANDING = "Playlist generated by CrateMine";
  const desc = description || "";
  let safeDescription: string;

  if (planConfig.removeBranding) {
    // Paid users: no forced branding
    safeDescription = desc;
  } else {
    // Free users: always include branding
    safeDescription = desc.includes(BRANDING)
      ? desc
      : desc
        ? `${desc}\n\n${BRANDING}`
        : BRANDING;
  }

  try {
    const playlist = await createPlaylist(
      title,
      safeDescription,
      sharing || "private",
      token,
      Array.isArray(trackIds) ? trackIds : undefined
    );
    return NextResponse.json({ playlist });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Creation failed";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
